### ISSUE TITLE
make install error 2

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubikey-ksm#23]
help2man -N --name='Print checksum of important database fields.  Useful for quickly determining whether several KSMs are in sync.' --version-string=1.16 ./ykksm-checksum > ykksm-checksum.1
    help2man: can't get `--help' info from ./ykksm-checksum
    Try `--no-discard-stderr' if option outputs to stderr
    Makefile:109: recipe for target 'ykksm-checksum.1' failed
    make: *** [ykksm-checksum.1] Error 2

**Comment by klali** [comment]
ykksm-checksum has a dependency on the DBI perl module. This should probably be made clearer.
